sudo: required
language: cpp

matrix:
  include:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
  - env: GCC_VERSION="4.9" GRSF_CACHE_DIR="$HOME/GRSFCache"
    os: linux
    dist: trusty
    compiler: gcc
    cache:
      timeout: 1000
      directories:
        - $GRSF_CACHE_DIR
    addons:
      apt:
        packages:
        - gcc-4.9
        - g++-4.9
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest

  #- env: CLANG_VERSION="3.7"
    #os: linux
    #dist: trusty
    #compiler: clang # eigen3 has still stome problems in Tensor.h
    #addons:
      #apt:
        #packages:
        #- clang-3.7
        #sources:
        #- ubuntu-toolchain-r-test
        #- llvm-toolchain-precise-3.7

  #- env: GCC_VERSION="4.9"
    #os: osx
    #compiler: gcc

  #- env: CLANG_VERSION="3.7"
    #os: osx
    #osx_image: xcode7
    #compiler: clang

# Install dependencies
install:

  - echo "Git version:"
  - git --version

  - export BUILD_CORES=2
  - export ROOT_PATH=`pwd`/..;
  - export CHECKOUT_PATH=`pwd`;
  - echo "ROOT_PATH= $ROOT_PATH"
  - echo "CHECKOUT_PATH= $CHECKOUT_PATH"

  - echo "GRSFramework version:"
  - git describe --tags --abbrev=10

  - chmod +x $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh
  - . $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh


script:
  - chmod +x $CHECKOUT_PATH/travis/build.sh
  - . $CHECKOUT_PATH/travis/build.sh

after_success:
  - cd $CHECKOUT_PATH
  - git reset --hard HEAD # Discard build artifacts
  - git clean -df # Discard build artifacts



notifications:
  email: false
