# Find Collision Library OZCOLLIDE
#
# OZCOLLIDE_FOUND
# OZCOLLIDE_INCLUDE_DIR      where to find the include files
# OZCOLLIDE_LIB_REL
# OZCOLLIDE_LIB_DBG
# OZCOLLIDE_REL
# OZCOLLIDE_DBG
# OZCOLLIDE_LIBRARIES


SET(OZCOLLIDE_SEARCH "C:/Develop/ozcollide" "C:/Develop/OZCOLLIDE")





FIND_PATH(OZCOLLIDE_INCLUDE_DIR "ozcollide/ozcollide.h" HINTS ${OZCOLLIDE_SEARCH} PATH_SUFFIXES "include") 

FIND_LIBRARY(OZCOLLIDE_LIB_REL "ozcollide.lib" HINTS ${OZCOLLIDE_SEARCH} PATH_SUFFIXES "lib" "lib/Release") 
FIND_LIBRARY(OZCOLLIDE_LIB_DBG "ozcollide.lib" HINTS ${OZCOLLIDE_SEARCH} PATH_SUFFIXES "lib" "lib/Debug") 
FIND_FILE(OZCOLLIDE_REL "ozcollide.dll" HINTS ${OZCOLLIDE_SEARCH} PATH_SUFFIXES "bin" "lib" "lib/Release" "bin/Release") 
FIND_FILE(OZCOLLIDE_DBG "ozcollide.dll" HINTS ${OZCOLLIDE_SEARCH} PATH_SUFFIXES "bin" "lib" "lib/Debug" "bin/Debug") 

SET(OZCOLLIDE_LIBRARIES "optimized" ${OZCOLLIDE_LIB_REL} "debug" ${OZCOLLIDE_LIB_DBG})

message(STATUS "OZCollide Include Dir: " ${OZCOLLIDE_INCLUDE_DIR})
STRING(COMPARE NOTEQUAL ${OZCOLLIDE_INCLUDE_DIR}  "OZCOLLIDE_INCLUDE_DIR-NOTFOUND" OZCOLLIDE_FOUND)

IF(NOT OZCOLLIDE_FOUND)
	IF(OZCOLLIDE_FIND_REQUIRED)
		message( FATAL_ERROR "OZCollide  Include directory was not found!")
	ELSE(OZCOLLIDE_FIND_REQUIRED)
		message( STATUS "OZCollide  Include directory was not found!")
	ENDIF(OZCOLLIDE_FIND_REQUIRED)
ELSE(NOT OZCOLLIDE_FOUND)
	message(STATUS "OZCollide  Include directory found!")
ENDIF(NOT OZCOLLIDE_FOUND)

MARK_AS_ADVANCED( OZCOLLIDE_INCLUDE_DIR )

