# Find Collision Library Opcode
#
# OPCODE_FOUND
# OPCODE_INCLUDE_DIR      where to find the include files
# OPCODE_LIB_REL
# OPCODE_LIB_DBG
# OPCODE_REL
# OPCODE_DBG
# OPCODE_LIBRARIES


SET(OPCODE_SEARCH "C:/Develop/OPCODE" "C:/Develop/Opcode")





FIND_PATH(OPCODE_INCLUDE_DIR "Opcode.h" HINTS ${OPCODE_SEARCH} PATH_SUFFIXES "include" ) 

FIND_LIBRARY(OPCODE_LIB_REL "Opcode.lib" HINTS ${OPCODE_SEARCH} PATH_SUFFIXES "lib") 
FIND_LIBRARY(OPCODE_LIB_DBG "Opcode_D.lib" HINTS ${OPCODE_SEARCH} PATH_SUFFIXES "lib") 
FIND_FILE(OPCODE_REL "Opcode.dll" HINTS ${OPCODE_SEARCH} PATH_SUFFIXES "bin" "lib") 
FIND_FILE(OPCODE_DBG "Opcode_D.dll" HINTS ${OPCODE_SEARCH} PATH_SUFFIXES "bin" "lib") 

SET(OPCODE_LIBRARIES "optimized" ${OPCODE_LIB_REL} "debug" ${OPCODE_LIB_DBG})

message(STATUS "OPCODE Include Dir: " ${OPCODE_INCLUDE_DIR})
STRING(COMPARE NOTEQUAL ${OPCODE_INCLUDE_DIR}  "OPCODE_INCLUDE_DIR-NOTFOUND" OPCODE_FOUND)

IF(NOT OPCODE_FOUND)
	IF(OPCODE_FIND_REQUIRED)
		message( FATAL_ERROR "OPCODE  Include directory was not found!")
	ELSE(OPCODE_FIND_REQUIRED)
		message( STATUS "OPCODE  Include directory was not found!")
	ENDIF(OPCODE_FIND_REQUIRED)
ELSE(NOT OPCODE_FOUND)
	message(STATUS "OPCODE  Include directory found!")
ENDIF(NOT OPCODE_FOUND)

MARK_AS_ADVANCED( OPCODE_INCLUDE_DIR )

