# Find STLSOFT Template Library
#
# TINYXML_FOUND
# TINYXML_INCLUDE_DIR      where to find the include files
# TINYXML_LIB_DEBUG
# TINYXML_LIB_RELEASE
# TINYXML_LIBRARIES

if(NOT $ENV{TINYXML})
message(WARNING "Environment TINYXML variable not set!")
endif(NOT $ENV{TINYXML})
SET(TINY_XML_SEARCH "C:/Develop/ticpp/")

message(STATUS "Environment TINYXML variable set to: $ENV{TINYXML}")
FIND_PATH(TINYXML_INCLUDE_DIR "ticpp.h" PATHS ${TINY_XML_SEARCH} PATH_SUFFIXES "include" ) 
FIND_LIBRARY(TINYXML_LIB_DEBUG "ticppd" PATHS ${TINY_XML_SEARCH} PATH_SUFFIXES "lib") 
FIND_LIBRARY(TINYXML_LIB_RELEASE "ticpp" PATHS ${TINY_XML_SEARCH} PATH_SUFFIXES "lib") 
message(STATUS "TinyXML Include Dir: " ${TINYXML_INCLUDE_DIR})
STRING(COMPARE NOTEQUAL ${TINYXML_INCLUDE_DIR}  "TINYXML_INCLUDE_DIR-NOTFOUND" TINYXML_FOUND)

IF(NOT TINYXML_FOUND)
	IF(TINYXML_FIND_REQUIRED)
		message( FATAL_ERROR "TinyXML Include directory was not found!")
	ELSE(TINYXML_FIND_REQUIRED)
		message( STATUS "TinyXML Include directory was not found!")
	ENDIF(TINYXML_FIND_REQUIRED)
ELSE(NOT TINYXML_FOUND)
	message(STATUS "TinyXML Include directory found!")
ENDIF(NOT TINYXML_FOUND)

MARK_AS_ADVANCED( TINYXML_INCLUDE_DIR )
MARK_AS_ADVANCED( TINYXML_LIB_DEBUG )
MARK_AS_ADVANCED( TINYXML_LIB_RELEASE )

SET(TINYXML_LIBRARIES "optimized" ${TINYXML_LIB_RELEASE} "debug" ${TINYXML_LIB_DEBUG})