# Find Eigen Template Library
#
# EIGEN_FOUND
# EIGEN_INCLUDE_DIR      where to find the include files


IF(WIN32)
SET( EIGEN_SEARCH C:/Develop/Eigen/ $ENV{EIGEN_HOME})
FIND_PATH(EIGEN_INCLUDE_DIR "Eigen/Eigen" PATHS ${EIGEN_SEARCH} ) 
message(STATUS "Eigen Include Dir: " ${EIGEN_INCLUDE_DIR})
STRING(COMPARE NOTEQUAL ${EIGEN_INCLUDE_DIR}  "EIGEN_INCLUDE_DIR-NOTFOUND" EIGEN_FOUND)
ELSEIF(UNIX)
SET( EIGEN_SEARCH /usr/local/include/ $ENV{EIGEN_HOME})
FIND_PATH(EIGEN_INCLUDE_DIR "Eigen/Eigen" PATHS ${EIGEN_SEARCH} ) 
message(STATUS "Eigen Include Dir: " ${EIGEN_INCLUDE_DIR})
STRING(COMPARE NOTEQUAL ${EIGEN_INCLUDE_DIR}  "EIGEN_INCLUDE_DIR-NOTFOUND" EIGEN_FOUND)
ELSE(UNIX)


IF(NOT EIGEN_FOUND)
	IF(EIGEN_FIND_REQUIRED)
		message( FATAL_ERROR "Eigen Library was not found!")
	ELSE(EIGEN_FIND_REQUIRED)
		message( STATUS "Eigen Library was not found!")
	ENDIF(EIGEN_FIND_REQUIRED)
ELSE(NOT EIGEN_FOUND)
	message(STATUS "Eigen found!")
ENDIF(NOT EIGEN_FOUND)


MARK_AS_ADVANCED( EIGEN_INCLUDE_DIR )
