(function(){function e(b,c){this.selector=null;c?this.nodes=c:"string"==typeof b?(this.selector=b,this.nodes=document.querySelectorAll(b)):this.nodes=[b];this.length=this.nodes.length;this.el=this.nodes[0]}function c(b){return new e(b)}function g(b,d){function l(a,c,d){a=a||{};e();!1!==c&&r();N=m=f=null;n=-1;D=A=E=F=null;B=!1;C=null;G=!1;q=null;g(a);x();S(f.transition_type,!0);m.find("#"+b+" .ism-caption").css("visibility","hidden");T();ca();y(f.play_type);da();setTimeout(function(){!0!==d&&k()},
1E3);console.log("ISMSlider Ready")}function e(){c("#"+b+"-ism-loading-mask").remove();var a=document.createElement("DIV");a.id=b+"-ism-loading-mask";a.style.position="absolute";a.style.zIndex=10;a.style.top=0;a.style.bottom=0;a.style.left=0;a.style.right=0;a.style.backgroundColor="#eee";c("#"+b).el.appendChild(a)}function k(){c("#"+b).show();1==c("#"+b+"-ism-loading-mask").length&&c("#"+b+"-ism-loading-mask").fadeOut(400,function(){c("#"+b+"-ism-loading-mask").remove();O(0);U(0)})}function g(a){for(var d in H){var h=
typeof H[d];void 0==a[d]&&"object"!=h&&(h=c("#"+b).data(d),void 0!=h&&(a[d]=h))}f=a||{};for(d in H)void 0==f[d]&&(f[d]=H[d]);f.captions=[];a=c("#"+b+" ol > li");d=a.length;for(h=0;h<d;h++){f.captions[h]=[];for(var l=0;3>l;l++){var u={enable:V[l].enable,delay:V[l].delay},e=c(a.get(h)).find(".ism-caption-"+l);1==e.length&&(u.enable=!0,e=e.data("delay"),isNaN(e)||(u.delay=parseInt(e)));f.captions[h][l]=u}}}function r(){h();W();q&&q.unbindEventListeners();X();c("#"+b+" .ism-radios input.ism-radio, #"+
b+" .ism-radios .ism-radio-label").off("click",I);c("#"+b+" .ism-radios input.ism-radio, #"+b+" .ism-radios .ism-radio-label").off("touchstart",I);Y();c("#"+b+" .ism-button").remove();c("#"+b+" .ism-radios").remove();c("#"+b+" .ism-cloned").remove();for(c("#"+b+" .ism-tmp-clone").remove();0<c("#"+b+" .ism-frame").length;)c("#"+b+" .ism-slides").unwrap();0<c("#"+b+" .ism-img-frame").length&&c("#"+b+" .ism-img").unwrap();c("#"+b+" .ism-caption").removeAttr("style");c("#"+b+" .ism-slide").show();c("#"+
b+" .ism-slide").removeAttr("style");c("#"+b+" .ism-slides").removeAttr("style");c("#"+b+" .ism-img").removeClass("ism-img");c("#"+b+" .ism-slide").removeClass("ism-slide ism-slide-0 ism-slide-1 ism-slide-2 ism-slide-3 ism-slide-4 ism-slide-5 ism-slide-6 ism-slide-7 ism-slide-8 ism-slide-9");c("#"+b+" .ism-slides").removeClass("ism-slides");c("#"+b).removeClass("active")}function x(){m=c("#"+b+" ol");N=100/c("#"+b+" ol > li").length;n=0;m.addClass("ism-slides");c("#"+b+" .ism-slides > li").addClass("ism-slide");
c("#"+b+" .ism-slides > .ism-slide > img, #"+b+" .ism-slides > .ism-slide > a > img").addClass("ism-img");m.find("li").each(function(a){this.addClass("ism-slide-"+a)});c("#"+b).wrapInner("<div class='ism-frame'></div>");m=c("#"+b+" ol.ism-slides");c("#"+b+" .ism-img").wrap("<div class='ism-img-frame'></div>")}function p(){return c("#"+b+" .ism-slide").length}function y(a){f.play_type=a;Y();c("#"+b+" .ism-pause-button").remove();f.pause_button&&"manual"!=f.play_type&&(m.after("<div class='ism-pause-button'>&nbsp;</div>"),
D=c("#"+b+" .ism-pause-button"),D.on("click",J),D.on("touchstart",J));t()}function t(){B=!0;c("#"+b+" .ism-pause-button").removeClass("ism-play");"manual"!=f.play_type&&(clearTimeout(C),C=setTimeout(a,f.interval))}function a(){var a=n+1;B&&"manual"!=f.play_type&&("once"==f.play_type&&n==p()-2?(z(a),h()):"once-rewind"==f.play_type&&n==p()-1?(z(0),h()):("loop"==f.play_type&&n==p()-1?z(0):z(a),t()))}function h(){B=!1;clearTimeout(C);C=null;c("#"+b+" .ism-pause-button").addClass("ism-play")}function u(a,
b){a!=n&&(h(),z(a,b))}function T(){f.buttons&&(m.after("<div class='ism-button ism-button-prev'>&nbsp;</div><div class='ism-button ism-button-next'>&nbsp;</div>"),F=c("#"+b+" .ism-button-prev"),E=c("#"+b+" .ism-button-next"),F.on("click",K),F.on("touchstart",K),E.on("click",L),E.on("touchstart",L))}function X(){c("#"+b+" .ism-button-prev").off("click",K);c("#"+b+" .ism-button-prev").off("touchstart",K);c("#"+b+" .ism-button-next").off("click",L);c("#"+b+" .ism-button-next").off("touchstart",L)}function K(a){a&&
a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation();u(n-1)}function L(a){a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation();u(n+1)}function ca(){if(f.radios){c("#"+b).append("<ul class='ism-radios'></ul>");A=c("#"+b+" .ism-radios");"thumbnail"==f.radio_type&&A.addClass("ism-radios-as-thumbnails");for(var a=0;a<p();a++)0==a?A.append("<li class='ism-radio-"+a+" active'><input type='radio' name='ism-radio' class='ism-radio' id='ism-radio-"+a+
"' checked='checked' /><label class='ism-radio-label' for='ism-radio-"+a+"'></label></li>"):A.append("<li class='ism-radio-"+a+"'><input type='radio' name='ism-radio' class='ism-radio' id='ism-radio-"+a+"' /><label class='ism-radio-label' for='ism-radio-"+a+"'></label></li>");c("#"+b+" .ism-radios input.ism-radio, #"+b+" .ism-radios .ism-radio-label").on("click",I);c("#"+b+" .ism-radios input.ism-radio, #"+b+" .ism-radios .ism-radio-label").on("touchstart",I)}}function I(a){a.preventDefault&&a.preventDefault();
a.stopPropagation&&a.stopPropagation();a=c(a.target.parentNode).index();u(a)}function Z(a){f.radios&&(c("#"+b+" .ism-radios li").removeClass("active"),a=c("#"+b+" .ism-radios li").get(a),c(a).addClass("active"),c(a).find("input").attr("checked","checked"))}function Y(){c("#"+b+" .ism-pause-button").off("click",J);c("#"+b+" .ism-pause-button").off("touchstart",J)}function J(a){a.preventDefault();a.stopPropagation();B?h():t()}function da(){var a=c("#"+b).get(0),d=m.get(0);q=new Dragdealer(a,d,{steps:p(),
x:0,speed:.2,loose:!0,requestAnimationFrame:!0,dragStartCallback:function(){h()},dragStopCallback:function(a,b){new_slide_index=q.getStep()[0]-1;h();var d=new_slide_index,c=n;n=d;P("afterswipe",[d]);Z(d);M(c,d,!1)},onAfterGlide:function(){q.setStep(n+1,1,!0)}});window.onload=function(){setTimeout(function(){q.reflow()},150);setTimeout(function(){q.reflow()},600)}}function aa(){q&&(q.setStep(n+1,1,!0),q.reflow())}function P(a,b){Q[a]&&Q[a].apply(this,b)}function S(a,d){if(1==d||a!=f.transition_type){f.transition_type=
a;c("#"+b+" .ism-slide").removeClass("ism-zoom-in");c("#"+b+" .ism-slide").show();var h=p();m.css("width",100*h+"%");m.find(".ism-slide").each(function(a){a=N*a+"%";this.css("width",100/h+"%");this.css("left",a)})}}function z(a,b){if(!0!==G&&a!=n){G=!0;var d=n;a=parseInt(a);0>a?a=p()-1:a>=p()&&(a=0);var h=a;Z(h);n=h;P("beforetransition",[h]);"instant"==f.transition_type?(h=a,q.setStep(h+1,1,!0),M(d,h,!0,b)):"slide"==f.transition_type?ea(d,a,b):"fade"==f.transition_type?ba(d,a,!1,b):"zoom"==f.transition_type&&
ba(d,a,!0,b)}}function ea(a,b,d){var h=b/(p()-1);q.startSlide(h,function(){M(a,b,!0,d)})}function ba(a,d,h,l){c("#"+b+" li.ism-slide").removeClass("ism-zoom-in");var u=c("#"+b+" li.ism-slide-"+a),e=m.clone();e.addClass("ism-slides-clone");var v=d/(p()-1),v=q.getOffsetsByRatios([v,0]);e.css("transform","translateX("+v[0]+"px)");e.insertAfter(m.el);h&&u.addClass("ism-zoom-in");e.fadeIn(2*f.transition_duration,function(){q.setStep(d+1,1,!0);c("#"+b+" .ism-slides-clone").remove();c("#"+b+" .ism-slides").show();
c("#"+b+" .ism-slides").css("opacity",null);M(a,d,!0,l);console.log("fadeIn ok")});m.fadeOut(1.8*f.transition_duration,function(){console.log("fadeOut ok")})}function M(a,d,h,l){d=parseInt(d);c("#"+b+" .ism-slides-clone").remove();c("#"+b+" .ism-slides").show();c("#"+b+" li.ism-slide").removeClass("ism-zoom-in");h&&aa();l&&l();O(d);U(d);G=!1;P("aftertransition",[d])}function O(a){W();"none"!=f.image_fx&&("zoompan"==f.image_fx?c("#"+b+" .ism-slide-"+a+" .ism-img-frame").addClass("ism-zoom-pan"):"zoomrotate"==
f.image_fx&&c("#"+b+" .ism-slide-"+a+" .ism-img-frame").addClass("ism-zoom-rotate"))}function W(){c("#"+b+" .ism-slide .ism-img-frame").removeClass("ism-zoom-pan");c("#"+b+" .ism-slide .ism-img-frame").removeClass("ism-zoom-rotate")}function U(a){m.find(".ism-caption").css("visibility","hidden");m.find(".ism-caption").removeClass("ism-caption-anim");R(a,0);R(a,1);R(a,2)}function R(a,b){f.captions[a]&&1==f.captions[a][b].enable&&setTimeout(function(){m.find(".ism-slide-"+a+" .ism-caption-"+b).css("visibility",
"visible");m.find(".ism-slide-"+a+" .ism-caption-"+b).addClass("ism-caption-anim")},f.captions[a][b].delay)}var H={transition_type:"slide",play_type:"manual",interval:7E3,image_fx:"none",buttons:!0,radios:!0,radio_type:"button",pause_button:!0,transition_duration:350,swipe:!0},V=[{enable:!1,delay:0},{enable:!1,delay:200},{enable:!1,delay:400}],f,m,N,n,F,E,A,D,B,C,G,q,Q={};l(d,!1,d.prevent_stop_loading||!1);this.init=l;this.deinit=r;this.stopLoading=k;this.transition=z;this.listen=function(a,b){Q[a]=
b};this.reflow=aa;this.setTransitionType=S;this.setPlayType=y;this.setInterval=function(a){f.interval=a};this.setImageFx=function(a){a!=f.image_fx?(f.image_fx=a,O(n)):f.image_fx=a};this.setCaptionEnable=function(a,b,d){f.captions[a][b].enable=d};this.setCaptionDelay=function(a,b,d){f.captions[a][b].delay=d};this.enableButtons=function(a){!0!==a||f.buttons||(X(),c("#"+b+" .ism-button").remove(),T())};this.enableRadios=function(a){};this.setRadioType=function(a){"thumbnail"==a?c("#"+b+" .ism-radios").addClass("ism-radios-as-thumbnails"):
c("#"+b+" .ism-radios").removeClass("ism-radios-as-thumbnails")};this.getSlideCount=p;this.getActiveSlideIndex=function(){return n};this.setElementId=function(a){b=document.getElementById(b).id=a}}e.prototype.get=function(b){return this.nodes[b]};e.prototype.find=function(b){b=this.el.querySelectorAll(b);return new e(null,b)};e.prototype.index=function(){for(var b=this.el,d=0;null!=(b=b.previousSibling);)d++;return d};e.prototype.each=function(b){for(var d=0;d<this.nodes.length;d++){var c=new e(this.nodes[d]);
b.call(c,d,c)}};e.prototype.remove=function(){for(var b=0;b<this.nodes.length;b++){var d=this.nodes[b];d.parentNode.removeChild(d)}};e.prototype.removeAttr=function(b){for(var d=0;d<this.nodes.length;d++)this.nodes[d].removeAttribute(b)};e.prototype.attr=function(b,d){var c=this.el;if(void 0!=d)c.setAttribute(b,d);else return c.getAttribute(b)};e.prototype.data=function(b){return this.el.getAttribute("data-"+b)};e.prototype.hasClass=function(b){var d=this.el;return d.classList?d.classList.contains(b):
(new RegExp("(^| )"+b+"( |$)","gi")).test(d.className)};e.prototype.addClass=function(b){for(var d=0;d<this.nodes.length;d++){var c=this.nodes[d];c.classList?c.classList.add(b):c.className+=" "+b}};e.prototype.removeClass=function(b){for(var d=0;d<this.nodes.length;d++){var c=this.nodes[d];c.classList?c.classList.remove(b.split(" ")):c.className=c.className.replace(new RegExp("(^|\\b)"+b.split(" ").join("|")+"(\\b|$)","gi")," ")}};e.prototype.show=function(){for(var b=0;b<this.nodes.length;b++){var d=
this.nodes[b];d&&d.style&&(d.style.display="")}};e.prototype.hide=function(){for(var b=0;b<this.nodes.length;b++){var d=this.el;d&&d.style&&(d.style.display="none")}};e.prototype.css=function(b,d){for(var c=0;c<this.nodes.length;c++)this.nodes[c].style[b]=d};e.prototype.fadeIn=function(b,d){var c=this.el;b=b||400;var e=0;c.style.opacity=0;c.style.filter="";var k=+new Date,g=function(){e+=(new Date-k)/b;c.style.opacity=e;c.style.filter="alpha(opacity="+100*e|NaN;k=+new Date;1>e?window.requestAnimationFrame&&
requestAnimationFrame(g)||setTimeout(g,16):d&&d()};g()};e.prototype.fadeOut=function(b,d){var c=this.el;b=b||400;var e=1;c.style.opacity=1;c.style.filter="";var k=+new Date,g=function(){e-=(new Date-k)/b;c.style.opacity=e;c.style.filter="alpha(opacity="+100*e|NaN;k=+new Date;0<e?window.requestAnimationFrame&&requestAnimationFrame(g)||setTimeout(g,16):d&&d()};g()};e.prototype.wrap=function(b){for(var d=0;d<this.nodes.length;d++){var c=this.nodes[d],g=(new e(c)).index(),k=c.outerHTML,w=c.parentNode;
c.insertAdjacentHTML("beforebegin",b);w.removeChild(c);w.childNodes[g].innerHTML=k}};e.prototype.wrapInner=function(b){var c=this.el,e=c.innerHTML;c.innerHTML=b;c.firstChild.innerHTML=e};e.prototype.unwrap=function(){var b=this.el;b.parentNode.outerHTML=b.parentNode.innerHTML};e.prototype.after=function(b){this.el.insertAdjacentHTML("afterend",b)};e.prototype.append=function(b){this.el.insertAdjacentHTML("beforeend",b)};e.prototype.insertAfter=function(b){b.parentNode.insertBefore(this.el,b.nextSibling)};
e.prototype.clone=function(){return new e(this.el.cloneNode(!0))};e.prototype.on=function(b,c){for(var e=0;e<this.nodes.length;e++){var g=this.nodes[e];g.addEventListener?g.addEventListener(b,c):g.attachEvent("on"+b,function(){c.call(g)})}};e.prototype.off=function(b,c){for(var e=0;e<this.nodes.length;e++){var g=this.nodes[e];g&&(g.removeEventListener?g.removeEventListener(b,c):g.detachEvent("on"+b,c))}};c.ready=function(b){console.log("document.readyState("+document.readyState+") document.addEventListener("+
!!document.addEventListener+")");"complete"===document.readyState?setTimeout(b,1):document.addEventListener?document.addEventListener("DOMContentLoaded",b,!1):document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&b()})};window.ISM=window.ISM||{};window.ISM.Slider=g;window.ISM.Config=window.ISM.Config||{};window.ISM.instances=[];c.ready(function(){console.log("iq.ready");if(!0!==window.ISM.Config.no_instantiation){var b=c(".ism-slider");console.log(b+" - "+b.length);
for(var d=0;d<b.length;d++){console.log("["+d+"]");var e=b.get(d);e.id=e.id||"ism-slider-"+d;window.ISM.instances.push(new g(e.id,{}))}}})})();
(function(e,c){"function"===typeof define&&define.amd?define(c):e.Dragdealer=c()})(this,function(){function e(a){var b=["Webkit","Moz","ms","O"],c=document.documentElement.style;if(void 0!==c[a])return a;a=a.charAt(0).toUpperCase()+a.substr(1);for(var d=0;d<b.length;d++)if(void 0!==c[b[d]+a])return b[d]+a}var c=function(a,b,c){this.options=this.applyDefaults(c||{});this.bindMethods();this.wrapper=a;this.handle=b;this.init();this.bindEventListeners()};c.prototype={defaults:{disabled:!1,horizontal:!0,
vertical:!1,slide:!0,steps:0,snap:!1,loose:!1,speed:.1,xPrecision:0,yPrecision:0,activeClass:"active",css3:!0,tapping:!0,afterSwipeCallback:function(){}},init:function(){if(this.options.css3){var a=this.handle;r.backfaceVisibility&&r.perspective&&(a.style[r.perspective]="1000px",a.style[r.backfaceVisibility]="hidden")}this.value={prev:[-1,-1],current:[this.options.x||0,this.options.y||0],target:[this.options.x||0,this.options.y||0]};this.offset={wrapper:[0,0],mouse:[0,0],prev:[-999999,-999999],current:[0,
0],target:[0,0]};this.change=[0,0];this.stepRatios=this.calculateStepRatios();this.sliding=this.tapping=this.dragging=this.activity=!1;this.slide_count=0;this.reflow();this.options.disabled&&this.disable()},applyDefaults:function(a){for(var b in this.defaults)a.hasOwnProperty(b)||(a[b]=this.defaults[b]);return a},calculateStepRatios:function(){var a=[];if(1<=this.options.steps)for(var b=0;b<=this.options.steps-1;b++)a[b]=1<this.options.steps?b/(this.options.steps-1):0;return a},setWrapperOffset:function(){this.offset.wrapper=
w.get(this.wrapper)},calculateBounds:function(){var a={top:this.options.top||0,bottom:-(this.options.bottom||0)+this.wrapper.offsetHeight,left:this.options.left||0,right:-(this.options.right||0)+this.wrapper.offsetWidth};a.availWidth=a.right-a.left-this.handle.offsetWidth;a.availHeight=a.bottom-a.top-this.handle.offsetHeight;return a},calculateValuePrecision:function(){var a=this.options.xPrecision||Math.abs(this.bounds.availWidth),b=this.options.yPrecision||Math.abs(this.bounds.availHeight);return[a?
1/a:0,b?1/b:0]},bindMethods:function(){this.requestAnimationFrame="function"===typeof this.options.customRequestAnimationFrame?g(this.options.customRequestAnimationFrame,window):g(p,window);this.cancelAnimationFrame="function"===typeof this.options.customCancelAnimationFrame?g(this.options.customCancelAnimationFrame,window):g(y,window);this.animateWithRequestAnimationFrame=g(this.animateWithRequestAnimationFrame,this);this.animate=g(this.animate,this);this.onHandleMouseDown=g(this.onHandleMouseDown,
this);this.onHandleTouchStart=g(this.onHandleTouchStart,this);this.onDocumentMouseMove=g(this.onDocumentMouseMove,this);this.onWrapperTouchMove=g(this.onWrapperTouchMove,this);this.onWrapperMouseDown=g(this.onWrapperMouseDown,this);this.onWrapperTouchStart=g(this.onWrapperTouchStart,this);this.onDocumentMouseUp=g(this.onDocumentMouseUp,this);this.onDocumentTouchEnd=g(this.onDocumentTouchEnd,this);this.onHandleClick=g(this.onHandleClick,this);this.onWindowResize=g(this.onWindowResize,this)},bindEventListeners:function(){b(this.handle,
"mousedown",this.onHandleMouseDown);b(this.handle,"touchstart",this.onHandleTouchStart);b(document,"mousemove",this.onDocumentMouseMove);b(this.wrapper,"touchmove",this.onWrapperTouchMove);b(this.wrapper,"mousedown",this.onWrapperMouseDown);b(this.wrapper,"touchstart",this.onWrapperTouchStart);b(document,"mouseup",this.onDocumentMouseUp);b(document,"touchend",this.onDocumentTouchEnd);b(this.handle,"click",this.onHandleClick);b(window,"resize",this.onWindowResize);this.animate(!1,!0);this.interval=
this.requestAnimationFrame(this.animateWithRequestAnimationFrame)},unbindEventListeners:function(){d(this.handle,"mousedown",this.onHandleMouseDown);d(this.handle,"touchstart",this.onHandleTouchStart);d(document,"mousemove",this.onDocumentMouseMove);d(this.wrapper,"touchmove",this.onWrapperTouchMove);d(this.wrapper,"mousedown",this.onWrapperMouseDown);d(this.wrapper,"touchstart",this.onWrapperTouchStart);d(document,"mouseup",this.onDocumentMouseUp);d(document,"touchend",this.onDocumentTouchEnd);d(this.handle,
"click",this.onHandleClick);d(window,"resize",this.onWindowResize);this.cancelAnimationFrame(this.interval)},onHandleMouseDown:function(a){a.target&&"A"==a.target.tagName&&0<=a.target.className.search(/ism-caption/)&&(document.location=a.target.href);k.refresh(a);l(a);v(a);this.activity=!1;this.startDrag()},onHandleTouchStart:function(a){a.target&&"A"==a.target.tagName&&0<=a.target.className.search(/ism-caption/)&&(document.location=a.target.href);k.refresh(a);v(a);this.activity=!1;this.startDrag()},
onDocumentMouseMove:function(a){k.refresh(a);this.dragging&&(this.activity=!0,l(a))},onWrapperTouchMove:function(a){k.refresh(a);!this.activity&&this.draggingOnDisabledAxis()?this.dragging&&this.stopDrag():(l(a),this.activity=!0)},onWrapperMouseDown:function(a){a.target&&0<=a.target.className.search(/ism-(button|radio|caption)/)||(k.refresh(a),l(a),this.startTap())},onWrapperTouchStart:function(a){k.refresh(a);l(a);this.startTap()},onDocumentMouseUp:function(a){this.stopDrag();this.stopTap();a.target&&
0<=a.target.className.search(/ism-(button|radio|caption)/)||this.options.afterSwipeCallback()},onDocumentTouchEnd:function(a){this.stopDrag();this.stopTap();this.options.afterSwipeCallback()},onHandleClick:function(a){a.target&&0<=a.target.className.search(/ism-(button|radio)/)||!this.activity||(l(a),v(a))},onWindowResize:function(a){this.reflow()},enable:function(){this.disabled=!1;this.handle.className=this.handle.className.replace(/\s?disabled/g,"")},disable:function(){this.disabled=!0;this.handle.className+=
" disabled"},reflow:function(){this.setWrapperOffset();this.bounds=this.calculateBounds();this.valuePrecision=this.calculateValuePrecision();this.updateOffsetFromValue()},getStep:function(){return[this.getStepNumber(this.value.target[0]),this.getStepNumber(this.value.target[1])]},getValue:function(){return this.value.target},setStep:function(a,b,c){this.setValue(this.options.steps&&1<a?(a-1)/(this.options.steps-1):0,this.options.steps&&1<b?(b-1)/(this.options.steps-1):0,c)},setValue:function(a,b,
c){this.setTargetValue([a,b||0]);c&&(this.groupCopy(this.value.current,this.value.target),this.updateOffsetFromValue(),this.callAnimationCallback())},startTap:function(){!this.disabled&&this.options.tapping&&(this.tapping=!0,this.setWrapperOffset(),this.setTargetValueByOffset([k.x-this.offset.wrapper[0]-this.handle.offsetWidth/2,k.y-this.offset.wrapper[1]-this.handle.offsetHeight/2]))},stopTap:function(){!this.disabled&&this.tapping&&(this.tapping=!1,this.setTargetValue(this.value.current))},startDrag:function(){this.disabled||
(this.dragging=!0,this.interval=this.requestAnimationFrame(this.animateWithRequestAnimationFrame),this.setWrapperOffset(),this.offset.mouse=[k.x-w.get(this.handle)[0],k.y-w.get(this.handle)[1]],this.wrapper.className.match(this.options.activeClass)||(this.wrapper.className+=" "+this.options.activeClass),this.callDragStartCallback())},stopDrag:function(){if(!this.disabled&&this.dragging){this.dragging=!1;var a=this.groupClone(this.value.current);if(this.options.slide){var b=this.change;a[0]+=4*b[0];
a[1]+=4*b[1]}this.setTargetValue(a);this.wrapper.className=this.wrapper.className.replace(" "+this.options.activeClass,"");this.callDragStopCallback()}},callAnimationCallback:function(){var a=this.value.current;this.options.snap&&1<this.options.steps&&(a=this.getClosestSteps(a));this.groupCompare(a,this.value.prev)||("function"==typeof this.options.animationCallback&&this.options.animationCallback.call(this,a[0],a[1]),this.groupCopy(this.value.prev,a))},callTargetCallback:function(){"function"==typeof this.options.callback&&
this.options.callback.call(this,this.value.target[0],this.value.target[1])},callDragStartCallback:function(){"function"==typeof this.options.dragStartCallback&&this.options.dragStartCallback.call(this,this.value.target[0],this.value.target[1])},callDragStopCallback:function(){"function"==typeof this.options.dragStopCallback&&this.options.dragStopCallback.call(this,this.value.target[0],this.value.target[1])},startSlide:function(a,b){this.slide_callback=b;this.sliding=!0;this.value.target[0]=a;this.slide_start=
this.value.current[0];this.step_size=Math.abs(this.value.target[0]-this.value.current[0]);this.interval=this.requestAnimationFrame(this.animateWithRequestAnimationFrame)},animateWithRequestAnimationFrame:function(a){a?(this.timeOffset=this.timeStamp?a-this.timeStamp:0,this.timeStamp=a):this.timeOffset=25;this.sliding?this.animateSlide():this.animate();if(this.sliding||this.dragging||this.value.target[0]!=this.value.current[0])this.interval=this.requestAnimationFrame(this.animateWithRequestAnimationFrame);
else this.options.onAfterGlide()},animate:function(a,b){if(!a||this.dragging){if(this.dragging){var c=this.groupClone(this.value.target);this.setTargetValueByOffset([k.x-this.offset.wrapper[0]-this.offset.mouse[0],k.y-this.offset.wrapper[1]-this.offset.mouse[1]],this.options.loose);this.change=[this.value.target[0]-c[0],this.value.target[1]-c[1]]}(this.dragging||b)&&this.groupCopy(this.value.current,this.value.target);if(this.dragging||this.glide()||b)this.updateOffsetFromValue(),this.callAnimationCallback()}},
glide:function(){var a=[this.value.target[0]-this.value.current[0],this.value.target[1]-this.value.current[1]];if(!a[0]&&!a[1])return!1;Math.abs(a[0])>this.valuePrecision[0]||Math.abs(a[1])>this.valuePrecision[1]?(this.value.current[0]+=a[0]*Math.min(this.options.speed*this.timeOffset/25,1),this.value.current[1]+=a[1]*Math.min(this.options.speed*this.timeOffset/25,1)):this.groupCopy(this.value.current,this.value.target);return!0},animateSlide:function(){for(var a=this.value.target[0]-this.value.current[0],
b=0<=a?1:-1,a=Math.abs(a),c=(this.value.current[0]-this.slide_start)/(this.value.target[0]-this.slide_start),d=c-.5,d=(-3*d*d+.8)*this.step_size*.08;d>a;)d*=.5;.995<c?(this.groupCopy(this.value.current,this.value.target),this.sliding=!1,this.slide_callback()):this.value.current[0]+=b*d;this.updateOffsetFromValue();this.renderHandlePosition();isNaN(c)},updateOffsetFromValue:function(){this.offset.current=this.options.snap?this.getOffsetsByRatios(this.getClosestSteps(this.value.current)):this.getOffsetsByRatios(this.value.current);
this.groupCompare(this.offset.current,this.offset.prev)||(this.renderHandlePosition(),this.groupCopy(this.offset.prev,this.offset.current))},renderHandlePosition:function(){var a="";this.options.css3&&r.transform?(this.options.horizontal&&(a+="translateX("+this.offset.current[0]+"px)"),this.handle.style[r.transform]=a):this.options.horizontal&&(this.handle.style.left=this.offset.current[0]+"px")},setTargetValue:function(a,b){var c=b?this.getLooseValue(a):this.getProperValue(a);this.groupCopy(this.value.target,
c);this.offset.target=this.getOffsetsByRatios(c);this.callTargetCallback()},setTargetValueByOffset:function(a,b){var c=this.getRatiosByOffsets(a),c=b?this.getLooseValue(c):this.getProperValue(c);this.groupCopy(this.value.target,c);this.offset.target=this.getOffsetsByRatios(c)},getLooseValue:function(a){var b=this.getProperValue(a);return[b[0]+(a[0]-b[0])/4,b[1]+(a[1]-b[1])/4]},getProperValue:function(a){a=this.groupClone(a);a[0]=Math.max(a[0],0);a[1]=Math.max(a[1],0);a[0]=Math.min(a[0],1);a[1]=Math.min(a[1],
1);(!this.dragging&&!this.tapping||this.options.snap)&&1<this.options.steps&&(a=this.getClosestSteps(a));return a},getRatiosByOffsets:function(a){return[this.getRatioByOffset(a[0],this.bounds.availWidth,this.bounds.left),this.getRatioByOffset(a[1],this.bounds.availHeight,this.bounds.top)]},getRatioByOffset:function(a,b,c){return b?(a-c)/b:0},getOffsetsByRatios:function(a){return[this.getOffsetByRatio(a[0],this.bounds.availWidth,this.bounds.left),this.getOffsetByRatio(a[1],this.bounds.availHeight,
this.bounds.top)]},getOffsetByRatio:function(a,b,c){return Math.round(a*b)+c},getStepNumber:function(a){return this.getClosestStep(a)*(this.options.steps-1)+1},getClosestSteps:function(a){return[this.getClosestStep(a[0]),this.getClosestStep(a[1])]},getClosestStep:function(a){for(var b=0,c=1,d=0;d<=this.options.steps-1;d++)Math.abs(this.stepRatios[d]-a)<c&&(c=Math.abs(this.stepRatios[d]-a),b=d);return this.stepRatios[b]},groupCompare:function(a,b){return a[0]==b[0]&&a[1]==b[1]},groupCopy:function(a,
b){a[0]=b[0];a[1]=b[1]},groupClone:function(a){return[a[0],a[1]]},draggingOnDisabledAxis:function(){return!this.options.horizontal&&k.xDiff>k.yDiff||!this.options.vertical&&k.yDiff>k.xDiff}};for(var g=function(a,b){return function(){return a.apply(b,arguments)}},b=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},d=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},l=function(a){a||(a=window.event);
a.preventDefault&&a.preventDefault();a.returnValue=!1},v=function(a){a||(a=window.event);a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},k={x:0,y:0,xDiff:0,yDiff:0,refresh:function(a){a||(a=window.event);"mousemove"==a.type?this.set(a):a.touches&&this.set(a.touches[0])},set:function(a){var b=this.x,c=this.y;if(a.clientX||a.clientY)this.x=a.clientX,this.y=a.clientY;else if(a.pageX||a.pageY)this.x=a.pageX-document.body.scrollLeft-document.documentElement.scrollLeft,this.y=a.pageY-document.body.scrollTop-
document.documentElement.scrollTop;this.xDiff=Math.abs(this.x-b);this.yDiff=Math.abs(this.y-c)}},w={get:function(a){var b={left:0,top:0};void 0!==a.getBoundingClientRect&&(b=a.getBoundingClientRect());return[b.left,b.top]}},r={transform:e("transform"),perspective:e("perspective"),backfaceVisibility:e("backfaceVisibility")},x=["webkit","moz"],p=window.requestAnimationFrame,y=window.cancelAnimationFrame,t=0;t<x.length&&!p;++t)p=window[x[t]+"RequestAnimationFrame"],y=window[x[t]+"CancelAnimationFrame"]||
window[x[t]+"CancelRequestAnimationFrame"];p||(p=function(a){return setTimeout(a,25)},y=clearTimeout);return c});
