# Find CEGUI Template Library
#
# CEGUI_FOUND
# CEGUI_INCLUDE_DIR      where to find the include files



SET( CEGUI_SEARCH C:/Develop/cegui/include/ C:/Develop//Dependencies/cegui/lib/)

FIND_PATH(CEGUI_INCLUDE_DIR "CEGUI.h" PATHS ${CEGUI_SEARCH} ) 
FIND_PATH( CEGUI_LIBRARY_DIR "Release/CEGUIBase.lib" PATHS ${CEGUI_SEARCH} )
FIND_PATH( CEGUI_LIBRARY_DIR "Debug/CEGUIBase.lib" PATHS ${CEGUI_SEARCH} )

message(STATUS "CEGUI Include Dir: " ${CEGUI_INCLUDE_DIR})
message(STATUS "CEGUI Libaray Dir: " ${CEGUI_LIBRARY_DIR})

STRING(COMPARE NOTEQUAL ${CEGUI_INCLUDE_DIR}  "CEGUI_INCLUDE_DIR-NOTFOUND" CEGUI_FOUND)
STRING(COMPARE NOTEQUAL ${CEGUI_LIBRARY_DIR}  "CEGUI_LIBRARY_DIR-NOTFOUND" CEGUI_FOUND)

IF(NOT CEGUI_FOUND)
	IF(CEGUI_FIND_REQUIRED)
		message( FATAL_ERROR "CEGUI Library was not found!")
	ELSE(CEGUI_FIND_REQUIRED)
		message( STATUS "CEGUI Library was not found!")
	ENDIF(CEGUI_FIND_REQUIRED)
ELSE(NOT CEGUI_FOUND)
	message(STATUS "CEGUI found!")
ENDIF(NOT CEGUI_FOUND)



MARK_AS_ADVANCED( CEGUI_INCLUDE_DIR CEGUI_LIBRARY_DIR)