# Find TOON Template Library
#
# TOON_FOUND
# TOON_INCLUDE_DIR      where to find the include files



SET( TOON_SEARCH C:/Develop/TooN/)

FIND_PATH(TOON_INCLUDE_DIR "TooN/TooN.h" PATHS ${TOON_SEARCH} ) 
message(STATUS "TooN Include Dir: " ${TOON_INCLUDE_DIR})
STRING(COMPARE NOTEQUAL ${TOON_INCLUDE_DIR}  "TOON_INCLUDE_DIR-NOTFOUND" TOON_FOUND)

IF(NOT TOON_FOUND)
	IF(TOON_FIND_REQUIRED)
		message( FATAL_ERROR "TooN Library was not found!")
	ELSE(TOON_FIND_REQUIRED)
		message( STATUS "TooN Library was not found!")
	ENDIF(TOON_FIND_REQUIRED)
ELSE(NOT TOON_FOUND)
	message(STATUS "TooN found!")
ENDIF(NOT TOON_FOUND)

MARK_AS_ADVANCED( TOON_INCLUDE_DIR )
